image: alpine:latest

stages:
- verify_build

before_script:
 - apk update && apk add libstdc++
 - apk add --update meson cmake alpine-sdk clang

build_gcc:
  stage: verify_build
  script:
    - mkdir build
    - CXX=g++ CC=gcc meson build
    - ninja -C build test
  artifacts:
    paths:
      - build/salmon/salmon
      - build/libsalmon_compiler.a

build_clang:
  stage: verify_build
  script:
    - mkdir build
    - CXX=clang++ CC=clang meson build
    - ninja -C build test
