image: opensuse/tumbleweed:latest

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID  
    - if: $CI_COMMIT_BRANCH == 'master' 

stages:
- verify_build

before_script:
 - zypper ref && zypper in -y meson cmake clang git gcc-c++ 

build_gcc:
  stage: verify_build
  script:
    - mkdir build
    - CXX=g++ CC=gcc meson build
    - ninja -C build test
  artifacts:
    paths:
      - build/salmon/salmon
      - build/libsalmon_compiler.a

build_clang:
  stage: verify_build
  script:
    - mkdir build
    - CXX=clang++ CC=clang meson build
    - ninja -C build test
